# Generated by Django 4.1.3 on 2022-12-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_orderitem_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='item',
        ),
    ]
